### ISSUE TITLE
Missing the Lighthouse

### ISSUE THREAD

**Issue by TuskenTimeTraveller** [standardebooks/edgar-allan-poe_short-fiction#2]
Considering the title and contents of this ebook, wouldn't it be missing "The Light-house"? It is debatably unfinished. But I do believe it is worthy of inclution in this collection. Thanks

**Comment by acabal** [comment]
@robinwhittleton, thoughts?

**Comment by TuskenTimeTraveller** [comment]
You can find it in The Life of Edgar Allan Poe (1909) - Volume II by George E. Woodberry. It is in the public domain, fortunately.

**Comment by TuskenTimeTraveller** [comment]
Would you like me to post the source?

**Comment by acabal** [comment]
Sure!

**Comment by TuskenTimeTraveller** [comment]
Here it is:

https://archive.org/details/lifeedgarallanp00unkngoog/page/n475/mode/2up

Although I just realized that it is a fragment. 

In wikisource the full text is available.

https://en.wikisource.org/wiki/(The_Light-House)

And in this website dedicated to Edgar All Poe the full text is also offered with annotations:

https://www.eapoe.org/works/mabbott/tom3t041.htm

Hope it is enough.

**Comment by acabal** [comment]
Robin this looks like an incomplete fragment, just a few sentences. I'm inclined not to include it. It's an academic curiosity, not a coherent work in any way.

**Comment by TuskenTimeTraveller** [comment]
It is incomplete in that source, I'm trying to find the full text.

**Comment by acabal** [comment]
There is no full text, [it was never completed.](https://en.wikipedia.org/wiki/The_Light-House)

**Comment by TuskenTimeTraveller** [comment]
I am aware of that. It is still included in most anthologies. That is why it should be considered for inclution.

**Comment by robinwhittleton** [comment]
I honestly can’t remember why I decided to skip it for this, but I’d be happy to include it you’d like to @acabal. It is unfinished, but then it also has significance as the last thing Poe wrote.

Note: there were other things that I deliberately didn’t include, like essays and deliberately misleading magazine articles.

**Comment by acabal** [comment]
@robinwhittleton if you don't feel strongly about it then I would rather not include it. It's an incomplete fragment, barely just started and not really coherent. It's interesting as an academic curiosity but it's not "short fiction" in any meaningful sense. It would be better included in a collection of Poe's ephemera, things like notebooks and sketches, etc., but those aren't the kinds of collections we work on.
